name: snu_graphics
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip
  # You can add more Conda packages here  
  # - numpy==1.23.1
  # - scipy
  - pip:
      - pyglet>=2.1.0
      # - another-pip-package